# Generated by Django 3.2.9 on 2021-11-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_tracker', '0002_auto_20211102_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistorytracker',
            name='user_agent',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
